---
title: "Assignments"
slug: assignments
---

# Preparation

<span class="newthought">You will get the most out of this class</span> if you (1) attend class, (2) complete all the readings, and (3) engage^[Take detailed notes, do follow-up reading on things, people, places you don't know about]  with the readings.


# Self-Assessment of Participation

Rather than take attendance or grade participation, I will ask you to send me an email giving an **honest** and **realistic** assessment of your participation in class. There will be three of these at different points in the semester.


Participation will cover (1) your attendance, (2) how much of the weekly readings you are completing, and (3) how much you are talking/answering/asking questions in class. You will give yourself a score from 0 to 10 and provide an explanation of why you deserve that score based on a rubric that I will make available.^[Note that I reserve the right to reject your score if it's outlandish.] 


# Pop Quizzes


I will hold somewhere between 6 and 20 pop quizzes (multiple choice, short-response) throughout the course of the semester. Pop quizzes will be administered at the start of class through Blackboard. 

Note that (apart from book chapters) I am not making the readings available on Blackboard; this means you probably won't have time to pull up unread PDFs mid-quiz.^[If you go through the trouble of finding and downloading the readings but not actually reading the papers then my hats off to you. You've beat me.] 

Pop quizzes will cover **the reading that was due for that week**. Uncompleted pop quizzes = 0, and they can't be made up. You can drop the lowest 20% of your pop quiz grades at the end of the course (this includes 0's for absences). 


# Midterm Exam

The midterm exam will be take-home. Make-up exams will be given only to students with medical or personal emergencies.  If an emergency arises, you will need to contact me **before** the exam or you will receive zero credit.

The midterm exam will cover material for the course up to that point in the semester, including both readings and lectures. As the semester progresses, I will populate [the reference page](/reference/) with key concepts and ideas you will need for the midterm exam. 


# Final Exam

A final exam will be held during exam week.  Make-up exams will be given only to students with medical or personal emergencies.  If an emergency arises, you will need to contact me **before** the exam or you will receive zero credit.

The final exam will cover all of the material from the course, including both readings and lectures. As the semester progresses, I will populate [the reference page](/reference/) with key concepts and ideas you will need for the final exam. 
