---
title: Reference
slug: reference
output:
  blogdown::html_page:
    template: ../pandoc/toc-title_html.template
    toc: true
---



# Things you should know for the Midterm



## Introduction to the course
## You should understand...


- ...how the new wave of Jihadi groups are similar and different to other armed actors
- ...the three different forms of warfare: conventional, SNC, irregular, and what each "looks" like
- ...how the rate of civil war *ocurrence* and *termination* has changed since the Cold War, and what explains these shifts
- ...what the "new" vs. "old" civil war debate was about, and whether this distinction really holds up

## On causes of war
## You should understand...

- ...the bargaining model of war:
    - why war can be thought of as "bargaining failure"
    - what factors make bargains difficult to reach, specifically the factors that impact *civil wars*
- ...the different *kinds* of grievances that sometimes motivate violence
- ...how *anomie* and changing demographics can contribute to violence
- ...why identity and ethnicity can become more or less salient in different contexts, and the implications salience has to violence
- ...what the **security dilemma** is and how it explains spirals of violence between groups
- ...how colonial rule can exacerbate ethnic tensions and produce conflict
- ...how Sunni and Shi'a relations were shaped by the US occupation (the Cockburn reading)
- ...how to situate the participation of wealthy slaveowners in the Confederacy in the "greed" vs. "grievance" debate
- ...how resource *lootability* and *commodity shocks* can makes conflict more or less likely, and how *opportunity costs* are part of the story
- ...why the kinds of resources groups have at *the start* of a conflict define how they behave *during* the conflict


## How wars are fought
## You should understand...


- ...what irregular warfare looks like, what the identification problem is, and how this impacts relations between civilians and combatants (both state and rebel)
- ...the distinction Kalyvas draws between *selective* and *indiscriminate* violence, with examples of each
- ...why indiscriminate violence is thought to be very costly and counterproductive
- ...when we are likely to see *indiscriminate* vs. *selective* violence
- ...why civilians would choose to accurately *denounce* someone, falsely *denounce* someone, or keep quiet
- ...the relationship between territorial control, denouncement, and selective violence (basically that crazy graph)
- ...that COIN varies along a continuum, and be able to describe what that continuum is
- ...the challenges that counterinsurgents face, the different objectives they wish to accomplish and how these objectives are often in tension with one another
- ...how troop quality and ability to monitor troops impacts counterinsurgency success, and how states manage trade-offs between troop quality and troop supply
- ...the general logic of "hearts and minds" approaches to COIN, how states pursue this strategy, and its limitations
- ...the tradeoffs *insurgents* face in using violence to accomplish goals
- ...why insurgents sometimes seek to disrupt *elections* and how they balance tradeoffs in wielding violence
- ...how the way that both states and rebel groups recruit new members can impact their interactions with and treatment of civilians


# Things you should know for the Final


## On the Colombian armed conflict
## You should understand...


- ...what paramilitary groups are, how they form, and the tradeoffs states face in relying on them vs. conventional security forces
- ...the broad strokes of the Colombian armed conflict: main actors, what they want, type of fighting
- ...what principal-agent problems are and their relevance for understanding paramilitary behavior
- ...the "land problem", both across the developing world and *specifically* in Colombia (esp. its relation to the armed conflict)
- ...what displacement is, why displaced people flee and why it's difficult for them to return
- ...what *strategic* displacement is, why armed actors strategically displace civilians, and how *elections* and *economic factors* play a role in displacement


## On the Peruvian armed conflict
## You should understand...

- ...the broad strokes of the Peruvian armed conflict: main actors, what they want, type of fighting
- ...the general outline of Shining Path ideology, and how ideology can generally help *and* hurt groups
- ...the response Shining Path got in Chuschi vs. Huanta and why they got those responses
- ...and how ideology and context interact to produce the good and bad responses Shining Path got in the La Serna book


## On contemporary criminal violence in Central America
## You should understand...

- ...the three factors making Central America so violent today
- ...why Guatemala has so much criminal violence, Nicaragua so little, and how the three factors explain this difference in outcomes
- ...how the quality of policing varies across Nicaragua and Guatemala, what policing looks like in each country
- ...the differences between the Nicaraguan Revolution and the Guatemalan Civil War and the implications this has for the quality of policing in each country today
- ...why, if the Nicaragua approach "works", other countries simply don't adopt it


## On order and governance
## You should understand...

- ...some of the public goods that rebels, gangs, and other armed actors provide for civilians in the places where they rule
- ...Olson's metaphor of the roving and stationary bandit, why each type of bandit does what it does, how time horizons figure into this, why civilians like stationary bandits, and how the metaphor helps us understand why so many armed groups provide governance
- ...the role gangs play in and outside of prisons, why the state can't easily replace them in that role, and how gangs enforce order/obedience
- ...what civilians and rebels "get" out of rebel governance, why rebel time horizons vary
- ...the ways in which rebels go above and beyond simply providing services and often "mimic" states through rituals and images, what purpose this serves
- ...why ISIS collects taxes even in resource-rich areas


## On ending conflicts
## You should understand...

- ...the general pros and cons of humanitarian intervention
- ...how US experience in Iraq and Afghanistan has colored current thinking about intervention
- ...the different forms of intervention, how they are supposed to work, how well they seem to work, and their limitations/costs
- ...the logic of partition, why proponents think it works, why opponents think it doesn't work
- ...the logic of power-sharing agreements, how well they seem to work, and why the quality of power-sharing agreements vary
- ...why wars often recur, with specific reference to our readings/lectures on Sunni-Shi'a relations in Iraq
- ...the pros and cons of involving civil society in peace-building