---
title: "Homework 3"
type: docs
output:
  blogdown::html_page:
    toc: true
editor_options: 
  chunk_output_type: console
menu:
  assignment:
    parent: Homeworks
    weight: 3
---




## Instructions



Answer the questions (below), and keep track of your answers somewhere (a notepad?). You will input your answers into Canvas. **Figure out the answers *BEFORE* opening Canvas**, otherwise you'll run out of time. 




## Tutorial


Skills used: 

- grouped summary counts
- grouped summary statistics


[My awkward Google Sheets video tutorials are here](https://www.dropbox.com/sh/rsj9qm67se619pm/AAD1wPt84O8yaIfSPcwN9edua?dl=0)


## The Vietnam War


Here, you'll be working with hamlet level data on territorial control, selective violence, and indiscriminate violence during the Vietnam War. Each row is a hamlet in a given month in the year 1969. Using the data (variable dictionary below), answer the following questions. 

<!-- Note: in 2-7 below you'll need to find how many X (bombs, hamlets, etc.) **total** happened in some unit (e.g., hamlets, area of control, etc.). But remember you have multiple months of observations per unit. So you'll need to add up all the X (e.g., bombs) in the unit (e.g., hamlet) to answer the question. -->


- Download this: <i class="fas fa-download"></i> [Vietnam HES data](/files/vietnam.csv)



1. What was the Strategic Hamlet Program during the Vietnam War? Look it up, describe in four to five sentences. Tell us what the program *did* and what its intended *objective* was. 


2. Take the SUM of the bombing variable across the hamlet ID variable. HOW MANY bomb sorties were launched against the most attacked hamlet in Vietnam, across all the months for which data is available?



3. Look at the PERCENT of hamlets in each control category. Overall, who had more control, the rebels, or the government?  



4. About HOW MANY MORE bomb sorties were aimed at places that had full rebel control than places where the government only had partial control? 



5. Take the SUM of selective terror events across the control variable. About HOW MANY cases of selective violence where there in hamlets where the government had full control? 


6. Take the SUM of selective terror events across the control variable. WHERE did rebels use more selective violence, where they had partial control or full control? And about how much more?



7. How different where the hamlets were Vietcong used selective violence than the hamlets they didn't use selective violence? Compare the AVERAGE levels of urban, population, development index, and buddhism in places with and without selective violence. 



8. Calculate the AVERAGE distance to the border across the areas of control variable. In general, what is the pattern? Do places under rebel control tend to be closer or further from the border? 




```{r, echo=FALSE,message=FALSE,warning=FALSE,results="asis"}
library(tidyverse)
library(pander)
tribble(~Variable, ~Description, 
        "hamlet_id", "9-digit HES identifier",
        "month", "Month",
        "selective_terror", "Did Vietcong use selective violence?",
        "control", "Who controlled hamlet?\n(1 = full state, 2 = partial state, 3 = contested, 4 = partial rebel, 5 = full rebel)",
        "bombed", "How many bombing sorties in hamlet?",
        "urban", "Is hamlet mostly urban?\n(1 = yes, 0 = no)",
        "pop", "Hamlet population",
        "border", "Distance to closest international border",
        "dev_index", "Development index (low to high)",
        "buddhist", "Predominantly Buddhist hamlet?\n(1 = yes, 0 = no)",
        "vietnamese", "Predominantly Vietnamese hamlet?\n(1 = yes, 0 = no)") %>% 
  pandoc.table()
```

