---
title: Assignment details
menu:
  assignment:
    parent: Overview
    weight: 1
type: docs
weight: 1
output:
  blogdown::html_page:
    toc: true
---


## Preparation

You will get the most out of this class if you (1) attend class, (2) complete all the readings, and (3) engage^[Take detailed notes, do follow-up reading on things, people, places you don't know about]  with the readings.



## Homework

To hone your data analysis and writing skills you will complete homework throughout the semester. Feel free to work together on the homework but *you must turn in your own answers.* You cannot work in groups of more than **two** people.


### Extensions on Homework


You can turn in the problem set one day late, no questions asked, though you will lose a letter-grade. Beyond that I will need formal, **written** documentation of the reason for missed work. If it's a medical emergency, this means a doctor's note, if this is a personal emergency, this means a signed letter from someone who can attest to the situation. 


**Note: So that I can return graded assignments in a timely manner, I will only consider extension requests up to a week out from the due date of the assignment.**


## Exams

There will be an in-class midterm and a final. The midterm will cover the first half of the course, the final will cover the second half. Format will be a combination of multiple choice and short response questions.


Exam questions are drawn from: 1) lectures, 2) readings, and 3) in-class activities. With (3), whatever I write on the board is fair game for exams. I will post study guides for each exams in the [reference](/reference/) section of the website. 



### Make-up exams

Make-up exams will be given *only* to students with medical or personal emergencies. If an emergency arises, you will need to contact me **before** the exam or you will receive zero credit. I will need formal, **written** documentation of the reason for the missed exam. If it's a medical emergency, this means a doctor's note, if this is a personal emergency, this means a signed letter from someone who can attest to the situation. 


## Grade disputes


If you believe that you received the wrong grade on an assignment or exam:


- send an email specifying **exactly** which questions you believe were graded incorrectly, and provide **specific** justification for why your answer is the correct one. We will then regrade your entire assignment. Your grade may go up, down, or stay the same
- Do not email to say you are generally unhappy with your grade, generally think it should be higher, or generally ask us to re-evaluate your grade
- I will **only accept grade appeals up to three days after the posting of a grade**